[general]
import = [
    "~/dotfiles/alacritty/catppuccin-mocha.toml"
]

[window]
padding={x=10,y=10}

[font]
normal={family="JetBrainsMono NF", style="Regular"}

[env]
TERM="xterm-256color"

[terminal]
shell="/bin/zsh"
