# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Floating windows
windowrule = match:class (org.telegram.desktop), float true, size 1000 600